[package]
name = "overlay-ne"
authors = ["Shota Shimazu <hornet.live.mf@gmail.com>"]
description = "Neural engine for CoreOverlay"
repository = "https://github.com/shotastage/OverlayNeuralEngine"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false


[lib]
name = "overlayne"
crate-type = [ "staticlib" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "3.1.1"
futures = "0.3.25"
anyhow = "1.0"
async-ffi = "0.4.0"
tokio = { version = "1.24.0", features = ["full"] }
safer-ffi = "0.0.10"
sha1 = "0.10.5"
swift-bridge = "0.1"


[build-dependencies]
build-deps = "0.1.4"
anyhow = "1.0"
glob = "0.3"
rustc_version = "0.4"
swift-bridge-build = "0.1"
cbindgen = "0.24.3"


[dev-dependencies]
anyhow = "1.0"
criterion = "0.3"
lazy_static = "1.4"
serial_test = "0.5"
tempfile = "3.1"
async-std = { version = "1.11.0", features = ["attributes"] }
async-executor = "1.4.1"
